# Generated by Django 4.0.3 on 2022-12-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_pedido_empleado_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
