# Generated by Django 3.0.2 on 2022-12-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_auto_20221216_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prioridad',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora',
            field=models.IntegerField(max_length=2),
        ),
    ]
