# Generated by Django 3.0.2 on 2022-12-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_auto_20221217_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='trabajando',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
