# Generated by Django 3.0.2 on 2022-12-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_empleado_trabajando'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='PagoxHora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
