# Generated by Django 3.0.2 on 2022-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_pedido_pagoxhora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='PagoxHora',
            new_name='pagoxHora',
        ),
        migrations.AddField(
            model_name='pedido',
            name='horaTrabajada',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
