# Generated by Django 3.0.2 on 2022-12-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_auto_20221218_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='diaTrabajado',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
