# Generated by Django 3.0.2 on 2022-12-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_pedido_diatrabajado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagoxHora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
