# Generated by Django 3.0.2 on 2022-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_auto_20221219_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='pago',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagoxHora',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
