# Generated by Django 3.0.2 on 2022-12-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0012_auto_20221219_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
