# Generated by Django 3.0.2 on 2022-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_pedido_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='totalPedido',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
