# Generated by Django 3.0.2 on 2022-12-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0014_empleado_totalpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombreEmpleado',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
