# Generated by Django 3.0.2 on 2022-12-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0015_pedido_nombreempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.TextField(max_length=30),
        ),
    ]
