# Generated by Django 3.0.2 on 2022-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_auto_20221220_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='diasTrabajados',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horasTrabajadas',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='empleado',
            name='pedidosTrabajados',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salFinSemana',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salHorasExtra',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salJorNorm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
