# Generated by Django 3.0.2 on 2022-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0017_auto_20221221_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salFinSemana',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salHorasExtra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salJorNorm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagoxHora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
